-- migrations.sql
CREATE DATABASE IF NOT EXISTS `lookbook` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `lookbook`;

-- users
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nome` VARCHAR(100) NOT NULL,
  `cognome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- products
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nome` VARCHAR(255) NOT NULL,
  `foto` JSON NOT NULL,
  `userId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_products_user` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- swap_orders
CREATE TABLE IF NOT EXISTS `swap_orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- pivot table swap_orders_products
CREATE TABLE IF NOT EXISTS `SwapOrderProducts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `swapOrderId` INT NOT NULL,
  `productId` INT NOT NULL,
  CONSTRAINT `fk_sop_swaporder` FOREIGN KEY (`swapOrderId`) REFERENCES `swap_orders`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sop_product` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- pivot table swap_orders_users
CREATE TABLE IF NOT EXISTS `SwapOrderUsers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `swapOrderId` INT NOT NULL,
  `userId` INT NOT NULL,
  CONSTRAINT `fk_sou_swaporder` FOREIGN KEY (`swapOrderId`) REFERENCES `swap_orders`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sou_user` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
